<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>d57a2c26-64c2-44fa-a7c8-edd4e8a51ff0</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\IspSession\IspSession.csproj" />
  </ItemGroup>

</Project>